server {
    listen 8080;
    server_name _;
    access_log /shared-logs/file_storage-access.log;
    error_log /shared-logs/file_storage-error.log warn;

    location / {
        auth_basic "Protected File Storage";
        auth_basic_user_file /etc/nginx/.htpasswd;

        autoindex off;
        alias /srv/uploads/;
        try_files $uri =404;
    }
}
